### ISSUE TITLE
Problem in meson build system

### ISSUE THREAD

**Issue by Priyeshkkumar** [nyorain/dlg#3]
When dlg is built with **default_library**=**shared** option, it works fine but when it's value is set to =**static** or =**both** the meson build system falis...
I think one of the variable **libtype** is incorrectly defined.
Please have a look into this, I am attaching the meson-log file...
Requesting to it fix it soon...

[meson-log(=both).txt](https://github.com/nyorain/dlg/files/4809347/meson-log.both.txt)
[meson-log(=static).txt](https://github.com/nyorain/dlg/files/4809348/meson-log.static.txt)

Also, could you please add respective code to produce a .lib file instead of .a file when dlg is built on windows
with **-Ddefault_library=static**

**Comment by nyorain** [comment]
Thanks, fixed the building for 'static' and 'both' (we are testing 'both' now on CI). I would not suggest using 'both' though, it's unclear how dependencies and pkgconfig files should be generated in that case (I defaulted to using the shared lib which might be unexpected).

Regarding the second problem, I found this meson issue: https://github.com/mesonbuild/meson/issues/1412. All I would accept is add an option (off by default) that does the proposed workaround to generate a .lib file, but I agree with the reasoning of the meson authors.

**Comment by nyorain** [comment]
Let me know if this fixes the issue for you. Btw, the easiest way to use dlg (at least if you only use it in a single project) is probably to just include the single source file `dlg.c` directly into your project instead of building a separate library.

**Comment by Priyeshkkumar** [comment]
> Regarding the second problem, I found this meson issue: [mesonbuild/meson#1412](https://github.com/mesonbuild/meson/issues/1412). All I would accept is add an option (off by default) that does the proposed workaround to generate a .lib file, but I agree with the reasoning of the meson authors.

I wanted to use the static version of dlg to link it with a Visual Studios solution and since VS does not accept **.a** file, therefore I asked for this feature...
But, since it is a default setup in meson, an option to control this behavior will be fine with me...
According to the discussion here: https://github.com/mesonbuild/meson/issues/1412 the **.lib** file which is generated only works on windows when **--buildtype release** flag is set and I also got it to this observations...
So, could you please make the **buildtype** to automatically set to **release**  when the option to generate **.lib** file is set...



> Let me know if this fixes the issue for you. Btw, the easiest way to use dlg (at least if you only use it in a single project) is probably to just include the single source file `dlg.c` directly into your project instead of building a separate library.

I wanted to use dlg as submodule in a project, and it would not be possible to directly use source files in the project...
Thanks, for your quick response...

**Comment by nyorain** [comment]
Are you sure that it only works in release mode for you? Can you test that manually? I don't think we can force meson to build a subproject in release mode (it's a global project setting in meson and can't be altered per subproject), so not sure how to fix it.

**Comment by Priyeshkkumar** [comment]
> Are you sure that it only works in release mode for you? Can you test that manually? I don't think we can force meson to build a subproject in release mode (it's a global project setting in meson and can't be altered per subproject), so not sure how to fix it.

Sorry, please ignore my reply to this topic...
The **static release** build is not working for me either...
And the problem to statically link dlg in a VS solution is still not soved for me... 
But, thanks for your responses...

**Comment by nyorain** [comment]
Why is it not working? Can you provide a log file or an error or something? It's tested manually and on CI and the library isn't very complex, it might be an issue with VS integration.
Also: what version on msvc are you using? Their standard C support isn't too great, compilation might be an issue on versions before 2015.

**Comment by Priyeshkkumar** [comment]
> Why is it not working? Can you provide a log file or an error or something? It's tested manually and on CI and the library isn't very complex, it might be an issue with VS integration.
> Also: what version on msvc are you using? Their standard C support isn't too great, compilation might be an issue on versions before 2015.

Sorry if I was not clear about my issue before...
I wanted to link dlg with a Visual Studios 2019 (MSVC 14.26.28801) solution. The current meson build system of dlg produces **.a** file for static build (I know it is a meson issue), and VS does not accept **.a** file for linking. And there is a requirement to statically link dlg.
Therefore I have to build dlg with **name_suffix : 'lib'**(https://github.com/mesonbuild/meson/issues/1412)  on windows to produce a **.lib** file to make it work...
Therefore I wanted an option or some other way to produce **.lib** file instead of **.a** when dlg is statically built on windows

> Sorry, please ignore my reply to this topic...
> The **static release** build is not working for me either...
> And the problem to statically link dlg in a VS solution is still not soved for me...
> But, thanks for your responses...


Sorry, I have forgotten to use #define DLG_STATIC before #include <dlg.h>, therefore it was not working...
After specifying the #define macro dlg(.lib file) is working fine for both debug and release modes...

But, please look into the issue of producing **.lib** file on windows...

Thanks

**Comment by nyorain** [comment]
Thanks for clarification!
> Sorry, I have forgotten to use #define DLG_STATIC before #include <dlg.h>, therefore it was not working...

Hm that's weird, when using dlg as subproject and the meson dependency, you should not even have to specify it. How are you linking to it? In meson, you usually do:

```
dep_dlg = dependency('dlg', fallback: ['dlg', 'dlg_dep'])
```
And then use that dependency in `dependencies` of your executable or library.
From my understanding of the meson issue, that should always work even if it's an `.a` instead of `.lib` file. I'll boot up windows later and just test it.

**Comment by Priyeshkkumar** [comment]
> Hm that's weird, when using dlg as subproject and the meson dependency, you should not even have to specify it. How are 
> you linking to it?

I have just started the integration of dlg in my project, therefore right now I am building dlg separately on Linux(Ubuntu), Windows and OS X and then linking dlg using **-ldlg** argument in Linux and OS X and **.lib** on Windows with a test program.
You can find details about my project - https://summerofcode.withgoogle.com/organizations/5537668068278272/

> In meson, you usually do:
> 
> ```
> dep_dlg = dependency('dlg', fallback: ['dlg', 'dlg_dep'])
> ```
> 
> And then use that dependency in `dependencies` of your executable or library.

Thanks, but the main project does not uses meson build system, it uses make and CMake, and VS solution on Windows therefore I would not be able to use this...

> From my understanding of the meson issue, that should always work even if it's an `.a` instead of `.lib` file.

I have also read about this - https://mesonbuild.com/FAQ.html#why-does-building-my-project-with-msvc-output-static-libraries-called-libfooa
But it does not worked for me until I used **.lib** file...

> I'll boot up windows later and just test it.

Thanks, I would really appreciate it...

**Comment by nyorain** [comment]
Alright, now I see your usecase. I added an option for it in #4, please have a look at that branch. Cool project though!

**Comment by Priyeshkkumar** [comment]
> Alright, now I see your usecase. I added an option for it in #4, please have a look at that branch. Cool project though!

Thanks
