### ISSUE TITLE
Compilation Issues in RVG and VPP

### ISSUE THREAD

**Issue by jdbener** [nyorain/dlg#6]
I wasn't sure where to report this. But when I try to compile pretty much any of your libraries DLG begins complaining about the DLG_CREATE_TAGS macro:

In file included from ../subprojects/dlg/include/dlg/dlg.hpp:18,
                 from ../subprojects/vpp/src/vpp/device.cpp:13:
../subprojects/vpp/src/vpp/device.cpp: In member function ‘void vpp::Device::init(nytl::Span<const std::pair<vk::Queue_T*, unsigned int> >)’:
../subprojects/dlg/include/dlg/dlg.h:93:3: error: expected primary-expression before ‘{’ token
   93 |   {DLG_DEFAULT_TAGS NULL, __VA_ARGS__, NULL}.begin()
      |   ^
../subprojects/dlg/include/dlg/dlg.h:189:22: note: in expansion of macro ‘DLG_CREATE_TAGS’
  189 |   dlg__do_log(level, DLG_CREATE_TAGS(NULL), DLG_FILE, __LINE__, __func__, NULL, #expr)
      |                      ^~~~~~~~~~~~~~~
../subprojects/dlg/include/dlg/dlg.h:231:26: note: in expansion of macro ‘dlg_assertl’
  231 | #define dlg_assert(expr) dlg_assertl(DLG_DEFAULT_ASSERT, expr)
      |                          ^~~~~~~~~~~
../subprojects/vpp/src/vpp/device.cpp:279:2: note: in expansion of macro ‘dlg_assert’
  279 |  dlg_assert(q);
      |  ^~~~~~~~~~

This issue occurs in a multitude of repetitions from both RVG and VPP.

`

**Comment by nyorain** [comment]
oh yeah thanks for the note! You just have to update dlg to master (go to the source folder in subprojects if you build via meson and switch to master with git). Will push a fix soon, together with a new dlg release.

**Comment by nyorain** [comment]
Should be fixed with the new release.
